spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_booking_db?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# 3.LOGGING SETUP: Turn off banner, keep logs clean, trace SQL bindings
spring.main.banner-mode=off
logging.level.root=warn
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# --- HIKARICP CONNECTION POOL SETTINGS ---
# Maximum number of active database connections in the pool
spring.datasource.hikari.maximum-pool-size=20
# Max time (in ms) a thread will wait for an available connection from the pool before throwing an error
spring.datasource.hikari.connection-timeout=5000

# --- TRANSACTION & LOCK TIMEOUT
# Max time (in ms) Hibernate will wait to acquire a pessimistic lock before giving up
spring.jpa.properties.jakarta.persistence.lock.timeout=3000

# --- JWT SECURITY ---
application.security.jwt.secret-key=${JWT_SECRET}

# --- REDIS ---
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=10m